language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-ci.sh
env:
  os:
  - linux
  - osx
  global:
  - PACKAGE=tyre
  matrix:
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.03
